# Site settings
title: システム屋まそお
email: 
description: "京都府舞鶴市でシステム開発を行うシステム屋まそおのWebサイト"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.masoo.jp" # the base hostname & protocol for your site

# Build settings
markdown: "kramdown"
future: true

paginate: 5
paginate_path: "/blog/:num/"

exclude: ["_sources", "README.md"]

# sitemap.xml
gems:
  - jekyll-sitemap
  - jekyll-paginate
